gitea = ["git.m5ka.dev"]
go = ["go.m5ka.dev"]
jenkins = ["ops.m5ka.dev"]
laenkea = ["wiki.laenkea.si", "www.laenkea.si", "laenkea.si"]
lamilioa = ["www.lamilioa.org", "lamilioa.org"]
m5ka = ["www.m5ka.dev", "m5ka.dev", "mariab.dev"]
makkulu = ["lang.kulupu.li"]
riyana = ["www.riyana.org", "riyana.org"]